Document: obmenu
Title: Debian obmenu Manual
Author: <insert document author here>
Abstract: This manual describes what obmenu is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/obmenu/obmenu.sgml.gz

Format: postscript
Files: /usr/share/doc/obmenu/obmenu.ps.gz

Format: text
Files: /usr/share/doc/obmenu/obmenu.text.gz

Format: HTML
Index: /usr/share/doc/obmenu/html/index.html
Files: /usr/share/doc/obmenu/html/*.html
