Document: screengen
Title: Debian screengen Manual
Author: <insert document author here>
Abstract: This manual describes what screengen is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/screengen/screengen.sgml.gz

Format: postscript
Files: /usr/share/doc/screengen/screengen.ps.gz

Format: text
Files: /usr/share/doc/screengen/screengen.text.gz

Format: HTML
Index: /usr/share/doc/screengen/html/index.html
Files: /usr/share/doc/screengen/html/*.html
